/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/console/v1/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Projects */
    get: operations["projects_console_v1_projects_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/console/v1/workspaces/{workspace_id}/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Overview */
    get: operations["overview_console_v1_workspaces__workspace_id__overview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/console/v1/workspaces/{workspace_id}/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Sessions */
    get: operations["sessions_console_v1_workspaces__workspace_id__sessions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/console/v1/projects/{project_id}/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Tasks */
    get: operations["tasks_console_v1_projects__project_id__tasks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/console/v1/projects/{project_id}/tasks/{task_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Task */
    get: operations["task_console_v1_projects__project_id__tasks__task_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/console/v1/workspaces/{workspace_id}/activity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Activity */
    get: operations["activity_console_v1_workspaces__workspace_id__activity_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/console/v1/workspaces/{workspace_id}/batches": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Batches */
    get: operations["batches_console_v1_workspaces__workspace_id__batches_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/console/v1/workspaces/{workspace_id}/rollouts/{rollout_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Rollout */
    get: operations["rollout_console_v1_workspaces__workspace_id__rollouts__rollout_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/console/v1/workspaces/{workspace_id}/sessions/{session_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Session */
    get: operations["session_console_v1_workspaces__workspace_id__sessions__session_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/console/v1/workspaces/{workspace_id}/batches/{batch_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Batch */
    get: operations["batch_console_v1_workspaces__workspace_id__batches__batch_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/console/v1/projects/{project_id}/memories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Memories */
    get: operations["memories_console_v1_projects__project_id__memories_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/console/v1/workspaces/{workspace_id}/memories/{memory_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Memory */
    get: operations["memory_console_v1_workspaces__workspace_id__memories__memory_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ActivityRow */
    ActivityRow: {
      /** Object Id */
      object_id: string;
      /** Kind */
      kind: string;
      /** Recorded At */
      recorded_at: string;
      /** Occurred At */
      occurred_at?: string | null;
      /** Object Type */
      object_type: string;
      /** Session Id */
      session_id?: string | null;
      /** Batch Id */
      batch_id?: string | null;
      /** Memory Id */
      memory_id?: string | null;
      /** Rollout Id */
      rollout_id?: string | null;
      /** Revision */
      revision?: number | null;
      /** Status */
      status: string;
    };
    /** BatchDetail */
    BatchDetail: {
      /** Batch Id */
      batch_id: string;
      /** Session Id */
      session_id: string;
      /** Task Id */
      task_id?: string | null;
      /** Status */
      status: string;
      /** Created At */
      created_at: string;
      /** Settled At */
      settled_at?: string | null;
      /**
       * Attempt Count
       * @default 0
       */
      attempt_count: number;
      /** Next Attempt At */
      next_attempt_at?: string | null;
      /** Last Error Class */
      last_error_class?: string | null;
      /** Rollout Id */
      rollout_id?: string | null;
      /**
       * Proposal Count
       * @default 0
       */
      proposal_count: number;
      /** Proposals */
      proposals: components["schemas"]["Proposal"][];
    };
    /** BatchLink */
    BatchLink: {
      /** Batch Id */
      batch_id: string;
      /** Status */
      status: string;
      /** Created At */
      created_at: string;
    };
    /** BatchRow */
    BatchRow: {
      /** Batch Id */
      batch_id: string;
      /** Session Id */
      session_id: string;
      /** Task Id */
      task_id?: string | null;
      /** Status */
      status: string;
      /** Created At */
      created_at: string;
      /** Settled At */
      settled_at?: string | null;
      /**
       * Attempt Count
       * @default 0
       */
      attempt_count: number;
      /** Next Attempt At */
      next_attempt_at?: string | null;
      /** Last Error Class */
      last_error_class?: string | null;
      /** Rollout Id */
      rollout_id?: string | null;
      /**
       * Proposal Count
       * @default 0
       */
      proposal_count: number;
    };
    /** Binding */
    Binding: {
      /** Task Id */
      task_id: string;
      /** Start Event Id */
      start_event_id: string;
      /** End Event Id */
      end_event_id: string | null;
    };
    /** Candidate */
    Candidate: {
      /** Candidate Id */
      candidate_id: string;
      /** Kind */
      kind: string;
      /** Status */
      status: string;
      /** Active Batch Id */
      active_batch_id: string | null;
    };
    /** Changes */
    Changes: {
      /** Operations */
      operations: {
        [key: string]: number;
      };
      /** Projection States */
      projection_states: {
        [key: string]: number;
      };
      /** Start */
      start: string;
      /** End */
      end: string;
    };
    /** Consumption */
    Consumption: {
      /** Receipt Id */
      receipt_id: string;
      /** Status */
      status: string;
      /** Created At */
      created_at: string;
    };
    /** Envelope[BatchDetail] */
    Envelope_BatchDetail_: {
      meta: components["schemas"]["SnapshotMeta"];
      data: components["schemas"]["BatchDetail"];
    };
    /** Envelope[MemoryDetail] */
    Envelope_MemoryDetail_: {
      meta: components["schemas"]["SnapshotMeta"];
      data: components["schemas"]["MemoryDetail"];
    };
    /** Envelope[Page[ActivityRow]] */
    Envelope_Page_ActivityRow__: {
      meta: components["schemas"]["SnapshotMeta"];
      data: components["schemas"]["Page_ActivityRow_"];
    };
    /** Envelope[Page[BatchRow]] */
    Envelope_Page_BatchRow__: {
      meta: components["schemas"]["SnapshotMeta"];
      data: components["schemas"]["Page_BatchRow_"];
    };
    /** Envelope[Page[MemoryRow]] */
    Envelope_Page_MemoryRow__: {
      meta: components["schemas"]["SnapshotMeta"];
      data: components["schemas"]["Page_MemoryRow_"];
    };
    /** Envelope[Page[SessionRow]] */
    Envelope_Page_SessionRow__: {
      meta: components["schemas"]["SnapshotMeta"];
      data: components["schemas"]["Page_SessionRow_"];
    };
    /** Envelope[Page[TaskRow]] */
    Envelope_Page_TaskRow__: {
      meta: components["schemas"]["SnapshotMeta"];
      data: components["schemas"]["Page_TaskRow_"];
    };
    /** Envelope[ProjectDirectory] */
    Envelope_ProjectDirectory_: {
      meta: components["schemas"]["SnapshotMeta"];
      data: components["schemas"]["ProjectDirectory"];
    };
    /** Envelope[RolloutDetail] */
    Envelope_RolloutDetail_: {
      meta: components["schemas"]["SnapshotMeta"];
      data: components["schemas"]["RolloutDetail"];
    };
    /** Envelope[SessionDetail] */
    Envelope_SessionDetail_: {
      meta: components["schemas"]["SnapshotMeta"];
      data: components["schemas"]["SessionDetail"];
    };
    /** Envelope[TaskRow] */
    Envelope_TaskRow_: {
      meta: components["schemas"]["SnapshotMeta"];
      data: components["schemas"]["TaskRow"];
    };
    /** Envelope[WorkspaceOverview] */
    Envelope_WorkspaceOverview_: {
      meta: components["schemas"]["SnapshotMeta"];
      data: components["schemas"]["WorkspaceOverview"];
    };
    /** EventRow */
    EventRow: {
      /** Event Id */
      event_id: string;
      /** Event Kind */
      event_kind: string;
      /** Occurred At */
      occurred_at: string;
      /** Received At */
      received_at: string;
    };
    /** Evidence */
    Evidence: {
      /** Evidence Id */
      evidence_id: string;
      /** Kind */
      kind: string;
      /** Excerpt */
      excerpt: string | null;
      source: components["schemas"]["Source"] | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Injection */
    Injection: {
      /** Receipt Id */
      receipt_id: string;
      /** Created At */
      created_at: string;
      /** Status */
      status: string | null;
      /** Reason */
      reason: string | null;
      /** Memory Ids */
      memory_ids: string[];
      /** Revisions */
      revisions: number[];
      /** Generation */
      generation: string | null;
      /** Ledger Sequence */
      ledger_sequence: number | null;
      /** Omissions */
      omissions: components["schemas"]["Omission"][];
      /** Bundle Digest */
      bundle_digest: string | null;
      /** Session Digest */
      session_digest: string | null;
      /** Consumption Records */
      consumption_records: components["schemas"]["Consumption"][];
    };
    JsonValue: unknown;
    /** Latency */
    Latency: {
      /** Samples */
      samples: number;
      /** P50 */
      p50: number | null;
      /** P95 */
      p95: number | null;
    };
    /** MemoryDetail */
    MemoryDetail: {
      /** Memory Id */
      memory_id: string;
      /** Current Revision */
      current_revision: number;
      /** Memory Type */
      memory_type: string;
      /** State */
      state: string;
      /** Conflict State */
      conflict_state: string;
      scope: components["schemas"]["MemoryScope"];
      /** Relations */
      relations: components["schemas"]["MemoryRelation"][];
      /** Revisions */
      revisions: components["schemas"]["Revision"][];
    };
    /** MemoryRelation */
    MemoryRelation: {
      /** Memory Id */
      memory_id: string;
      /**
       * Relation
       * @enum {string}
       */
      relation: "replaces" | "replaced_by";
    };
    /** MemoryRow */
    MemoryRow: {
      /** Memory Id */
      memory_id: string;
      /** Current Revision */
      current_revision: number;
      /** Memory Type */
      memory_type: string;
      /** State */
      state: string;
      /** Conflict State */
      conflict_state: string;
      /** Scope Kind */
      scope_kind: string;
      /** Created At */
      created_at: string;
      payload: components["schemas"]["JsonValue"];
    };
    /** MemoryScope */
    MemoryScope: {
      /** Kind */
      kind: string;
      /** Project Id */
      project_id?: string | null;
      /** Path Pattern */
      path_pattern?: string | null;
      /** Task Id */
      task_id?: string | null;
    };
    /** Module[Changes] */
    Module_Changes_: {
      /**
       * Availability
       * @enum {string}
       */
      availability: "available" | "unavailable";
      value?: components["schemas"]["Changes"] | null;
      /** Reason */
      reason?: string | null;
    };
    /** Module[Page[ActivityRow]] */
    Module_Page_ActivityRow__: {
      /**
       * Availability
       * @enum {string}
       */
      availability: "available" | "unavailable";
      value?: components["schemas"]["Page_ActivityRow_"] | null;
      /** Reason */
      reason?: string | null;
    };
    /** Module[Page[SessionRow]] */
    Module_Page_SessionRow__: {
      /**
       * Availability
       * @enum {string}
       */
      availability: "available" | "unavailable";
      value?: components["schemas"]["Page_SessionRow_"] | null;
      /** Reason */
      reason?: string | null;
    };
    /** Module[Page[TaskRow]] */
    Module_Page_TaskRow__: {
      /**
       * Availability
       * @enum {string}
       */
      availability: "available" | "unavailable";
      value?: components["schemas"]["Page_TaskRow_"] | null;
      /** Reason */
      reason?: string | null;
    };
    /** Module[RolloutDetail] */
    Module_RolloutDetail_: {
      /**
       * Availability
       * @enum {string}
       */
      availability: "available" | "unavailable";
      value?: components["schemas"]["RolloutDetail"] | null;
      /** Reason */
      reason?: string | null;
    };
    /** Module[RuntimeStatus] */
    Module_RuntimeStatus_: {
      /**
       * Availability
       * @enum {string}
       */
      availability: "available" | "unavailable";
      value?: components["schemas"]["RuntimeStatus"] | null;
      /** Reason */
      reason?: string | null;
    };
    /** Observation */
    Observation: {
      /** Yes */
      yes: number;
      /** No */
      no: number;
      /** Unknown */
      unknown: number;
      /** Labeled Samples */
      labeled_samples: number;
      /** Evaluated Samples */
      evaluated_samples: number;
      /** Yes Rate */
      yes_rate: number | null;
    };
    /** Omission */
    Omission: {
      /** Memory Id */
      memory_id: string;
      /** Revision */
      revision: number;
      /** Reason */
      reason: string;
    };
    /** Page[ActivityRow] */
    Page_ActivityRow_: {
      /** Items */
      items: components["schemas"]["ActivityRow"][];
      /** Next Cursor */
      next_cursor?: string | null;
    };
    /** Page[BatchRow] */
    Page_BatchRow_: {
      /** Items */
      items: components["schemas"]["BatchRow"][];
      /** Next Cursor */
      next_cursor?: string | null;
    };
    /** Page[MemoryRow] */
    Page_MemoryRow_: {
      /** Items */
      items: components["schemas"]["MemoryRow"][];
      /** Next Cursor */
      next_cursor?: string | null;
    };
    /** Page[SessionRow] */
    Page_SessionRow_: {
      /** Items */
      items: components["schemas"]["SessionRow"][];
      /** Next Cursor */
      next_cursor?: string | null;
    };
    /** Page[TaskRow] */
    Page_TaskRow_: {
      /** Items */
      items: components["schemas"]["TaskRow"][];
      /** Next Cursor */
      next_cursor?: string | null;
    };
    /** Project */
    Project: {
      /** Project Id */
      project_id: string;
      /** Name */
      name: string;
      /** Workspaces */
      workspaces: components["schemas"]["Workspace"][];
    };
    /** ProjectDirectory */
    ProjectDirectory: {
      /** Items */
      items: components["schemas"]["Project"][];
    };
    /** Proposal */
    Proposal: {
      /** Proposal Id */
      proposal_id: string;
      /** Candidate Id */
      candidate_id: string;
      /** Operation */
      operation: string;
      /** Target Id */
      target_id: string | null;
      /** Expected Revision */
      expected_revision: number | null;
      /** Status */
      status: string;
      scope: components["schemas"]["MemoryScope"] | null;
      old_payload: components["schemas"]["JsonValue"];
      new_payload: components["schemas"]["JsonValue"];
      /** Rationale */
      rationale: string | null;
      /** Evidence */
      evidence: components["schemas"]["Evidence"][];
      /** Availability */
      availability: string;
    };
    /** Revision */
    Revision: {
      /** Revision */
      revision: number;
      /** Operation */
      operation: string;
      /** Created At */
      created_at: string;
      payload: components["schemas"]["JsonValue"];
      /** Evidence */
      evidence: components["schemas"]["Evidence"][];
    };
    /** Rollback */
    Rollback: {
      /** States */
      states: {
        [key: string]: number;
      };
      /** Audit */
      audit: {
        [key: string]: number;
      };
    };
    /** RolloutDetail */
    RolloutDetail: {
      /** Rollout Id */
      rollout_id: string;
      /** Mode */
      mode: string;
      /** Status */
      status: string;
      /** Started At */
      started_at: string;
      /** Deadline */
      deadline: string;
      /** Stop Reason */
      stop_reason: string | null;
      /** Generation */
      generation: string;
      /** Session Reservations */
      session_reservations: number;
      /** Session Limit */
      session_limit: number;
      /** Candidate Reservations */
      candidate_reservations: number;
      /** Candidate Limit */
      candidate_limit: number;
      /** Batches */
      batches: {
        [key: string]: number;
      };
      /** Reviews */
      reviews: {
        [key: string]: number;
      };
      /** Proposals */
      proposals: {
        [key: string]: number;
      };
      judge_latency_ms: components["schemas"]["Latency"];
      /** Consumption Reports */
      consumption_reports: number;
      /** Observations */
      observations: {
        [key: string]: components["schemas"]["Observation"];
      };
      /** Projection States */
      projection_states: {
        [key: string]: number;
      };
      rollback: components["schemas"]["Rollback"];
      /** Quality Status */
      quality_status: string;
    };
    /** RuntimeStatus */
    RuntimeStatus: {
      /** Configured Mode */
      configured_mode: string;
      /** Persisted Status */
      persisted_status: string | null;
      /** Effective Mode */
      effective_mode: string;
      /** Block Reason */
      block_reason: string | null;
      /** Scheduler */
      scheduler: string;
      /** Other Workspace Id */
      other_workspace_id: string | null;
    };
    /** SessionDetail */
    SessionDetail: {
      /** Session Id */
      session_id: string;
      /** Host */
      host: string;
      /** Opened At */
      opened_at: string;
      /** Closed At */
      closed_at?: string | null;
      /** Task Id */
      task_id?: string | null;
      /** Last Event At */
      last_event_at?: string | null;
      /** Events */
      events: components["schemas"]["EventRow"][];
      /** Batches */
      batches: components["schemas"]["BatchLink"][];
      /** Candidates */
      candidates: components["schemas"]["Candidate"][];
      /** Injections */
      injections: components["schemas"]["Injection"][];
      /** Bindings */
      bindings: components["schemas"]["Binding"][];
      /** Truncated */
      truncated: string[];
    };
    /** SessionRow */
    SessionRow: {
      /** Session Id */
      session_id: string;
      /** Host */
      host: string;
      /** Opened At */
      opened_at: string;
      /** Closed At */
      closed_at?: string | null;
      /** Task Id */
      task_id?: string | null;
      /** Last Event At */
      last_event_at?: string | null;
    };
    /** SnapshotMeta */
    SnapshotMeta: {
      /**
       * Observed At
       * Format: date-time
       */
      observed_at: string;
      /** Schema Version */
      schema_version: number;
      /** Ledger Sequence */
      ledger_sequence: number;
      /** Request Id */
      request_id: string;
    };
    /** Source */
    Source: {
      /** Event Id */
      event_id: string;
      /** Session Id */
      session_id: string;
      /** Event Kind */
      event_kind: string;
      /** Received At */
      received_at: string;
    };
    /** TaskRow */
    TaskRow: {
      /** Task Id */
      task_id: string;
      /** Project Id */
      project_id: string;
      /** Goal */
      goal: string;
      /** Status */
      status: string;
      /** Created At */
      created_at: string;
      /** Last Active */
      last_active: string;
      /** Session Id */
      session_id?: string | null;
      /** Checkpoint At */
      checkpoint_at?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** Workspace */
    Workspace: {
      /** Workspace Id */
      workspace_id: string;
      /** Name */
      name: string;
    };
    /** WorkspaceOverview */
    WorkspaceOverview: {
      /** Workspace Id */
      workspace_id: string;
      /** Project Id */
      project_id: string;
      runtime: components["schemas"]["Module_RuntimeStatus_"];
      tasks: components["schemas"]["Module_Page_TaskRow__"];
      sessions: components["schemas"]["Module_Page_SessionRow__"];
      rollout: components["schemas"]["Module_RolloutDetail_"];
      memory_changes: components["schemas"]["Module_Changes_"];
      activity: components["schemas"]["Module_Page_ActivityRow__"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  projects_console_v1_projects_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Envelope_ProjectDirectory_"];
        };
      };
    };
  };
  overview_console_v1_workspaces__workspace_id__overview_get: {
    parameters: {
      query: {
        start: string;
        end: string;
      };
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Envelope_WorkspaceOverview_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sessions_console_v1_workspaces__workspace_id__sessions_get: {
    parameters: {
      query?: {
        cursor?: string | null;
        limit?: number;
      };
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Envelope_Page_SessionRow__"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  tasks_console_v1_projects__project_id__tasks_get: {
    parameters: {
      query?: {
        workspace_id?: string | null;
        cursor?: string | null;
        limit?: number;
      };
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Envelope_Page_TaskRow__"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  task_console_v1_projects__project_id__tasks__task_id__get: {
    parameters: {
      query: {
        workspace_id: string;
      };
      header?: never;
      path: {
        project_id: string;
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Envelope_TaskRow_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  activity_console_v1_workspaces__workspace_id__activity_get: {
    parameters: {
      query: {
        start: string;
        end: string;
        kinds?: string[];
        cursor?: string | null;
        limit?: number;
      };
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Envelope_Page_ActivityRow__"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  batches_console_v1_workspaces__workspace_id__batches_get: {
    parameters: {
      query?: {
        status?: string | null;
        cursor?: string | null;
        limit?: number;
      };
      header?: never;
      path: {
        workspace_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Envelope_Page_BatchRow__"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  rollout_console_v1_workspaces__workspace_id__rollouts__rollout_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
        rollout_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Envelope_RolloutDetail_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  session_console_v1_workspaces__workspace_id__sessions__session_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspace_id: string;
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Envelope_SessionDetail_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  batch_console_v1_workspaces__workspace_id__batches__batch_id__get: {
    parameters: {
      query?: {
        project_id?: string | null;
        task_id?: string | null;
        touched_paths?: string[];
      };
      header?: never;
      path: {
        workspace_id: string;
        batch_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Envelope_BatchDetail_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  memories_console_v1_projects__project_id__memories_get: {
    parameters: {
      query: {
        workspace_id: string;
        task_id?: string | null;
        touched_paths?: string[];
        cursor?: string | null;
        limit?: number;
        view?: string;
      };
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Envelope_Page_MemoryRow__"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  memory_console_v1_workspaces__workspace_id__memories__memory_id__get: {
    parameters: {
      query?: {
        project_id?: string | null;
        task_id?: string | null;
        touched_paths?: string[];
      };
      header?: never;
      path: {
        workspace_id: string;
        memory_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Envelope_MemoryDetail_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
