"""Install SagaContext V1 locally; installation starts with rollout disabled.

The default operation only checks prerequisites and writes a local config template.
It never enables rollout mode, reads secret values, starts a daemon, or changes hooks
unless the corresponding explicit option is supplied.
"""
from __future__ import annotations

import argparse, json, os, shutil, subprocess, sys, tomllib
from pathlib import Path
if __package__ in {None, ""}: sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from scripts.setup_support import atomic_write, deployment_status, hook_config, install_hooks, merged_hooks, owned_process, setup_lock, start_daemon, stop_daemon

VERSION = "1.0.0"
HOST_VERSION = "codex-cli 0.153.4"


def run(command: list[str], *, cwd: Path, dry_run: bool = False) -> None:
    print("step:", Path(command[0]).name, " ".join(command[1:]))
    if not dry_run: subprocess.run(command, cwd=cwd, check=True)


def config_text(home: Path, *, port: int, workspace: Path | None = None) -> str:
    return f'''# SagaContext V1 local configuration. Generated by sagacontext_setup.py.
# Installation starts in read-only mode; keep rollout.mode=off until separately authorized.
[daemon]
host = "127.0.0.1"
port = {port}

[rollout]
mode = "off"
worker_enabled = false
workspace = {json.dumps(str(workspace) if workspace else "")}
host = "codex"
host_version = "{HOST_VERSION}"
stop_file = {json.dumps(str(home / "STOP"))}

[openviking]
base_url = "http://127.0.0.1:1933"
# api_key_file = "/absolute/path/to/a-protected-file"

[llm]
# base_url, api_key_file and model are intentionally not generated with values.
'''


def check_codex_version() -> None:
    executable = shutil.which("codex")
    if not executable:
        raise ValueError(f"missing prerequisite: codex (required version {HOST_VERSION})")
    result = subprocess.run([executable, "--version"], text=True, capture_output=True, check=False)
    version = result.stdout.strip()
    if result.returncode != 0 or version != HOST_VERSION:
        raise ValueError(f"Codex version mismatch: expected {HOST_VERSION}, found {version or 'unknown'}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--home", type=Path, default=Path.home() / ".sagacontext")
    parser.add_argument("--workspace", type=Path, help="workspace that receives Codex hooks")
    parser.add_argument("--port", type=int)
    parser.add_argument("--with-hooks", action="store_true")
    parser.add_argument("--remove-hooks", action="store_true")
    parser.add_argument("--with-console", action="store_true")
    parser.add_argument("--with-openviking", action="store_true", help="start the pinned local sidecar")
    parser.add_argument("--start", action="store_true", help="start the daemon after checks")
    parser.add_argument("--stop", action="store_true")
    parser.add_argument("--install-service", action="store_true")
    parser.add_argument("--remove-service", action="store_true")
    parser.add_argument("--status", action="store_true")
    parser.add_argument("--open-console", action="store_true", help="open /console/ after the daemon starts")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)
    root = args.root.expanduser().resolve(); home = args.home.expanduser().resolve()
    if not (root / "pyproject.toml").is_file():
        parser.error(f"not a SagaContext checkout: {root}")
    if args.open_console and not args.start:
        parser.error("--open-console requires --start")
    if args.install_service and args.remove_service:
        parser.error("choose one service operation")
    if args.with_hooks and args.remove_hooks:
        parser.error("choose --with-hooks or --remove-hooks")
    operations = sum(bool(value) for value in (args.stop, args.status, args.remove_hooks, args.install_service, args.remove_service))
    if operations > 1:
        parser.error("choose one lifecycle operation")
    if (args.stop or args.status or args.remove_service) and any(
        bool(value) for value in (args.with_console, args.with_openviking, args.start, args.with_hooks)
    ):
        parser.error("lifecycle operations cannot be combined with install options")
    print(f"SagaContext {VERSION} setup")
    print("root:", root)
    print("home:", home)
    workspace = args.workspace.expanduser().resolve() if args.workspace else None
    if (args.with_hooks or args.remove_hooks) and not workspace: parser.error("hook operations require --workspace")
    config_path = home / "config.toml"
    try: config_data = tomllib.loads(config_path.read_text()) if config_path.exists() else {}
    except (ValueError, UnicodeError): raise ValueError("config.toml is invalid; existing contents preserved")
    daemon = config_data.get("daemon", {}) if isinstance(config_data.get("daemon", {}), dict) else {}
    rollout = config_data.get("rollout", {}) if isinstance(config_data.get("rollout", {}), dict) else {}
    port = daemon.get("port", args.port if args.port is not None else 37780)
    if type(port) is not int or not 1024 <= port <= 65535: raise ValueError("daemon port must be between 1024 and 65535")
    if args.port is not None and config_path.exists() and args.port != port: raise ValueError("--port conflicts with existing config")
    if daemon.get("host", "127.0.0.1") != "127.0.0.1": raise ValueError("installer requires daemon.host = 127.0.0.1")
    if (args.start or args.install_service) and (rollout.get("mode", "off") != "off" or rollout.get("worker_enabled", False) is not False): raise ValueError("managed startup requires rollout.mode=off and worker_enabled=false")
    if args.with_hooks or args.remove_hooks: merged_hooks(workspace / ".codex" / "hooks.json", root, home, remove=args.remove_hooks)
    if args.with_hooks: check_codex_version()
    if args.with_hooks and config_path.exists():
        configured = rollout.get("workspace", "")
        values = [configured] if isinstance(configured, str) else configured
        if not isinstance(values, list) or str(workspace) not in [str(Path(v).expanduser().resolve()) for v in values if isinstance(v, str)]:
            raise ValueError("existing rollout.workspace does not include the requested workspace; edit it explicitly first")
    if args.with_console and not shutil.which("npm"): raise ValueError("missing prerequisite: npm")
    if args.with_openviking:
        if not (root / "OpenViking" / "docker-compose.yml").is_file(): raise ValueError("OpenViking/docker-compose.yml is missing")
        if not shutil.which("docker"): raise ValueError("missing prerequisite: docker")
    if args.status:
        value = deployment_status(port); print("daemon:", "managed and running" if owned_process(home) else "reachable (not setup-owned)" if value else "unreachable"); print("backend reachability: unchecked"); return 0 if value else 1
    if args.dry_run: print("dry-run: preflight passed; no files, dependencies, hooks or services changed"); return 0
    if args.stop: stop_daemon(home); return 0
    if args.remove_hooks:
        install_hooks(workspace, root, home, remove=True)
        return 0
    if args.remove_service:
        from scripts.setup_support import manage_service
        manage_service(root, home, remove=True, dry_run=args.dry_run)
        return 0
    uv = shutil.which("uv")
    if not uv: raise ValueError("missing prerequisite: uv")
    with setup_lock(home):
      run([uv, "sync", "--locked"], cwd=root, dry_run=False)
      if args.with_console:
          npm = shutil.which("npm")
          if not npm: raise ValueError("missing prerequisite: npm")
          run([npm, "ci"], cwd=root / "web", dry_run=False)
          run([npm, "run", "build"], cwd=root / "web", dry_run=False)
      config = home / "config.toml"
      if not config.exists(): atomic_write(config, config_text(home, port=port, workspace=workspace).encode()); print("created:", config)
      else: print("kept existing:", config)
    if args.with_openviking:
        compose = root / "OpenViking" / "docker-compose.yml"
        run(["docker", "compose", "up", "-d", "openviking"], cwd=compose.parent, dry_run=False)
    if args.with_hooks:
        install_hooks(workspace, root, home)
    if args.start:
        start_daemon(root, home, port)
    if args.install_service:
        from scripts.setup_support import manage_service
        manage_service(root, home, remove=False)
    print("rollout mode: off (no hooks or ingestion are enabled by default)")
    print("next: edit the protected config, run config-doctor, then explicitly authorize integration")
    if args.open_console:
        import webbrowser; webbrowser.open(f"http://127.0.0.1:{port}/console/deployment")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, subprocess.SubprocessError) as exc:
        print("setup:", str(exc), file=sys.stderr)
        raise SystemExit(1)
